/**
 * @dezin/core — domain types + the local-first metadata store.
 */

export type {
  Project,
  Conversation,
  Variant,
  Message,
  Run,
  Artifact,
  Moodboard,
  MoodboardNode,
  MoodboardNodeType,
  MoodboardAsset,
  MoodboardConversation,
  MoodboardMessage,
  MessageRole,
  RunStatus,
  CreateProjectInput,
  CreateMoodboardInput,
  CreateEffectInput,
  Effect,
  EffectOrigin,
  EffectParamDefinition,
  EffectParamKind,
  EffectParamOption,
  EffectParamValue,
  EffectPreset,
  UpdateEffectInput,
  SaveMoodboardNodeInput,
  Settings,
  QualityFinding,
  QualityIgnoreEntry,
  ExtensionScope,
  ExtensionCredential,
  ExtensionCredentialRecord,
} from "./types.ts";
export type {
  ArtifactKind,
  ApprovedProposalResult,
  ArtifactPublicationExpectation,
  ArtifactQualityProfile,
  ArtifactQualityState,
  ArtifactQualitySummary,
  ArtifactRevisionDependency,
  ArtifactRevisionDependencyInput,
  ArtifactRevisionResourcePin,
  ArtifactRevisionResourcePinInput,
  BrokenPrototypeEdge,
  ComponentInstanceDependencyStatus,
  ComponentPropagationOverrideResolution,
  ComponentPropagationProposalPayload,
  CreateWorkspaceProposalInput,
  CreateArtifactRevisionInput,
  CreateKernelRevisionInput,
  DesignNodeLocator,
  InteractivePrototypeEdge,
  KernelImpactAnalysis,
  KernelImpactArtifactRevision,
  KernelPublicationExpectation,
  LegacyGitSnapshot,
  LegacyWorkspaceFacts,
  LegacyWorkspaceProjectFact,
  LegacyWorkspaceRunFact,
  LegacyWorkspaceSeed,
  LegacyWorkspaceVariantFact,
  LayoutBounds,
  GenerationPlan,
  GenerationPlanStatus,
  NewWorkspaceEdge,
  NewWorkspaceNode,
  PlannedPrototypeEdge,
  ProjectWorkspace,
  PrototypeBinding,
  PrototypeEdge,
  PrototypeEdgeStatus,
  PrototypeTransition,
  PrototypeTrigger,
  RenderFrameSpec,
  ResourceKind,
  ResourcePinPolicy,
  SharedDesignKernelRevision,
  WorkspaceArtifactNode,
  WorkspaceEdge,
  WorkspaceEdgeKind,
  WorkspaceGraph,
  WorkspaceGraphCommand,
  WorkspaceGraphMutationInput,
  WorkspaceGraphMutationResult,
  WorkspaceGenerationArtifactPlan,
  WorkspaceGenerationCapability,
  WorkspaceGenerationDependencyPlan,
  WorkspaceGenerationPayload,
  WorkspaceGenerationPrototypeIntent,
  WorkspaceGenerationResourceOperation,
  WorkspaceLayout,
  WorkspaceLayoutCommand,
  WorkspaceLayoutGroup,
  WorkspaceLayoutNode,
  WorkspaceLayoutPatch,
  WorkspaceNode,
  WorkspaceNodeKind,
  WorkspaceProposal,
  WorkspaceProposalApprovalMode,
  WorkspaceProposalGeneration,
  WorkspaceProposalKind,
  WorkspaceProposalReview,
  WorkspaceProposalStatus,
  WorkspaceResourceRevisionPolicy,
  WorkspaceResourceNode,
  WorkspaceSnapshot,
  WorkspaceSnapshotPublicationInput,
  WorkspaceSnapshotProvenance,
  WorkspaceViewport,
  UpdateWorkspaceProposalInput,
} from "./workspace-types.ts";
export {
  WorkspaceCommandReplayConflictError,
  WorkspaceGraphValidationError,
  WorkspaceRevisionConflictError,
  applyWorkspaceGraphCommands,
  normalizeWorkspaceGraphCommands,
  validateWorkspaceGraph,
} from "./workspace-graph.ts";
export {
  LegacyWorkspaceSeedDriftError,
  WorkspaceLayoutConflictError,
  WorkspacePointerConflictError,
  WorkspaceProposalConflictError,
  WorkspaceProposalNotFoundError,
  WorkspaceProposalOwnershipError,
  WorkspaceProposalRevisionConflictError,
  WorkspaceProposalStateConflictError,
  WorkspaceProposalValidationError,
  WorkspaceStore,
  type WorkspaceProposalConflictSummary,
  type WorkspacePointerKind,
} from "./workspace-store.ts";
export {
  WorkspaceStoreCodecError,
  asGenerationPlan,
  asWorkspaceLayoutValue,
  asWorkspaceProposal,
  asWorkspaceProposalAudit,
  asWorkspaceProposalValue,
  normalizeCreateWorkspaceProposalInput,
  normalizeWorkspaceGraphMutationInput,
  normalizeWorkspaceLayoutCommands,
  normalizeWorkspaceLayoutPatch,
  normalizeWorkspaceProposalApprovalMode,
  normalizeWorkspaceProposalGeneration,
  normalizeUpdateWorkspaceProposalInput,
  workspaceLayoutChecksum,
  type ArtifactRevisionDependencyRecord,
  type ArtifactRevisionRecord,
  type ArtifactRevisionResourcePinRecord,
  type ArtifactTrackRecord,
  type WorkspaceArtifactRecord,
  type WorkspaceBundle,
  type WorkspaceProposalRecord,
  type GenerationPlanRecord,
  type WorkspaceSnapshotBaseRecord,
  type WorkspaceSnapshotRecord,
} from "./workspace-codecs.ts";
export { Store, type StoreClock } from "./store.ts";
