/**
 * Serve a generated artifact file from an on-disk artifact directory, with
 * path-traversal protection. Prototype artifacts live at <dataDir>/projects/<id>/...
 * while Standard variants may live in git worktrees.
 */

import { readFile, stat } from "node:fs/promises";
import { join, resolve, sep } from "node:path";
import type { ServerResponse } from "node:http";
import { send, sendError, contentTypeFor } from "./http-util.ts";

export function projectDir(dataDir: string, projectId: string): string {
  return join(dataDir, "projects", projectId);
}

/**
 * A tiny element-picker bridge injected into served prototype HTML. The workspace
 * toggles it via postMessage; on click it reports the clicked element's selector +
 * text back to the parent, so the user can point at a region and refine it in chat.
 */
const SELECT_BRIDGE = `<script data-dezin-bridge>(function(){
var bridge=window.__dezinBridgeTransport;if(!bridge)return;
var installPicker=!window.__dezinSelect,installScroll=!window.__dezinScrollSync;if(!installPicker&&!installScroll)return;window.__dezinSelect=1;window.__dezinScrollSync=1;
var on=false,pinned=false,hoverBox,selectedBox,selectedEl,keyboardEl=null,keyboardIndex=-1,liveRegion;
function mkbox(){hoverBox=document.createElement('div');hoverBox.style.cssText='position:fixed;pointer-events:none;z-index:2147483646;border:2px solid #2563eb;background:rgba(37,99,235,.10);border-radius:3px;display:none';document.body.appendChild(hoverBox);selectedBox=document.createElement('div');selectedBox.style.cssText='position:fixed;pointer-events:none;z-index:2147483647;border:2px solid #f97316;background:rgba(249,115,22,.14);border-radius:3px;display:none';document.body.appendChild(selectedBox);liveRegion=document.createElement('div');liveRegion.setAttribute('role','status');liveRegion.setAttribute('aria-live','polite');liveRegion.setAttribute('aria-atomic','true');liveRegion.style.cssText='position:fixed;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap;pointer-events:none';document.body.appendChild(liveRegion);}
function announce(value){if(liveRegion)liveRegion.textContent=value;}
function css(v){try{return CSS&&CSS.escape?CSS.escape(v):v.replace(/[^a-zA-Z0-9_-]/g,'\\\\$&');}catch(_){return v;}}
function attr(v){return String(v).replace(/\\\\/g,'\\\\\\\\').replace(/"/g,'\\\\"');}
function nth(el){var i=1,n=el;while((n=n.previousElementSibling)){if(n.tagName===el.tagName)i++;}return i;}
function stable(el){var design=el.getAttribute&&el.getAttribute('data-design-node-id');if(design)return '[data-design-node-id="'+attr(design)+'"]';var target=el.getAttribute&&el.getAttribute('data-dezin-id');if(target)return '[data-dezin-id="'+attr(target)+'"]';var node=el.getAttribute&&el.getAttribute('data-dezin-node-id');if(node)return '[data-dezin-node-id="'+attr(node)+'"]';var label=el.getAttribute&&el.getAttribute('data-screen-label');if(label)return '[data-screen-label="'+attr(label)+'"]';if(el.id)return el.tagName.toLowerCase()+'#'+css(el.id);return '';}
function path(el){if(!el||el===document.body||el===document.documentElement)return el?el.tagName.toLowerCase():'';var exact=stable(el);if(exact)return exact;var parts=[],n=el,depth=0;while(n&&n.nodeType===1&&n!==document.body&&depth<5){var st=stable(n);if(st){parts.unshift(st);break;}var p=n.tagName.toLowerCase();if(n.classList&&n.classList.length)p+='.'+[].slice.call(n.classList).slice(0,2).map(css).join('.');p+=':nth-of-type('+nth(n)+')';parts.unshift(p);n=n.parentElement;depth++;}return parts.join(' > ');}
function locator(el){var n=el,marked=null;while(n&&n.nodeType===1&&n!==document.body){var nodeId=(n.getAttribute&&n.getAttribute('data-design-node-id'))||(n.getAttribute&&n.getAttribute('data-dezin-id'))||(n.getAttribute&&n.getAttribute('data-dezin-node-id'));if(nodeId){marked=n;break;}n=n.parentElement;}var target=marked||el,selector=path(target),designNodeId=(target.getAttribute&&target.getAttribute('data-design-node-id'))||(target.getAttribute&&target.getAttribute('data-dezin-id'))||(target.getAttribute&&target.getAttribute('data-dezin-node-id'))||'selector:'+selector,sourceNode=target,sourcePath='';while(sourceNode&&sourceNode.nodeType===1&&!sourcePath){sourcePath=(sourceNode.getAttribute&&sourceNode.getAttribute('data-dezin-source-path'))||(sourceNode.getAttribute&&sourceNode.getAttribute('data-source-path'))||'';sourceNode=sourceNode.parentElement;}var result={designNodeId:String(designNodeId),selector:selector};if(sourcePath)result.sourcePath=sourcePath;return{element:target,locator:result,instanceId:(target.getAttribute&&target.getAttribute('data-dezin-instance-id'))||''};}
function attrs(el){try{var cls=typeof el.className==='string'?el.className:(el.getAttribute&&el.getAttribute('class'))||'';return{id:el.id||'',className:cls,role:(el.getAttribute&&el.getAttribute('role'))||'',ariaLabel:(el.getAttribute&&el.getAttribute('aria-label'))||'',screenLabel:(el.getAttribute&&el.getAttribute('data-screen-label'))||'',designNodeId:(el.getAttribute&&el.getAttribute('data-design-node-id'))||'',dezinId:(el.getAttribute&&el.getAttribute('data-dezin-id'))||(el.getAttribute&&el.getAttribute('data-dezin-node-id'))||'',sourcePath:(el.getAttribute&&el.getAttribute('data-dezin-source-path'))||(el.getAttribute&&el.getAttribute('data-source-path'))||'',instanceId:(el.getAttribute&&el.getAttribute('data-dezin-instance-id'))||'',href:(el.getAttribute&&el.getAttribute('href'))||'',src:(el.getAttribute&&el.getAttribute('src'))||''};}catch(_){return{};}}
function styles(el){try{var s=getComputedStyle(el);return{display:s.display,position:s.position,top:s.top,right:s.right,bottom:s.bottom,left:s.left,zIndex:s.zIndex,width:s.width,height:s.height,minWidth:s.minWidth,maxWidth:s.maxWidth,minHeight:s.minHeight,maxHeight:s.maxHeight,overflow:s.overflow,overflowX:s.overflowX,overflowY:s.overflowY,flexDirection:s.flexDirection,flexWrap:s.flexWrap,justifyContent:s.justifyContent,alignItems:s.alignItems,alignContent:s.alignContent,gap:s.gap,rowGap:s.rowGap,columnGap:s.columnGap,gridTemplateColumns:s.gridTemplateColumns,gridTemplateRows:s.gridTemplateRows,padding:s.padding,margin:s.margin,color:s.color,background:s.backgroundColor,backgroundImage:s.backgroundImage,fontFamily:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,lineHeight:s.lineHeight,letterSpacing:s.letterSpacing,textAlign:s.textAlign,textTransform:s.textTransform,borderRadius:s.borderRadius,opacity:s.opacity,borderColor:s.borderColor,borderWidth:s.borderWidth,borderStyle:s.borderStyle,borderTopColor:s.borderTopColor,borderTopWidth:s.borderTopWidth,borderTopStyle:s.borderTopStyle,borderRightColor:s.borderRightColor,borderRightWidth:s.borderRightWidth,borderRightStyle:s.borderRightStyle,borderBottomColor:s.borderBottomColor,borderBottomWidth:s.borderBottomWidth,borderBottomStyle:s.borderBottomStyle,borderLeftColor:s.borderLeftColor,borderLeftWidth:s.borderLeftWidth,borderLeftStyle:s.borderLeftStyle,outlineColor:s.outlineColor,outlineWidth:s.outlineWidth,outlineStyle:s.outlineStyle,boxShadow:s.boxShadow,filter:s.filter,backdropFilter:s.backdropFilter,transform:s.transform,mixBlendMode:s.mixBlendMode};}catch(_){return{};}}
function place(box,r){if(!box)return;box.style.display='block';box.style.left=r.left+'px';box.style.top=r.top+'px';box.style.width=r.width+'px';box.style.height=r.height+'px';}
function fit(el,box){if(!box||!el)return;place(box,el.getBoundingClientRect());}
function fitRect(box,rect){if(!box||!rect)return;box.style.display='block';box.style.left=rect.x+'px';box.style.top=rect.y+'px';box.style.width=rect.w+'px';box.style.height=rect.h+'px';}
function refreshSelected(){if(selectedEl)fit(selectedEl,selectedBox);}
function move(e){if(!on)return;fit(e.target,hoverBox);}
function wholeText(value){if(value.length>100000)return false;for(var i=0;i<value.length;i++){var code=value.charCodeAt(i);if(code>=55296&&code<=56319){var next=value.charCodeAt(i+1);if(next<56320||next>57343)return false;i++;}else if(code>=56320&&code<=57343)return false;}return true;}
function previewText(value){return value.replace(/\\s+/g,' ').trim().slice(0,160);}
function choose(target){if(!target||target.nodeType!==1)return;var picked=locator(target),el=picked.element,r=el.getBoundingClientRect(),tag=el.tagName.toLowerCase(),text=String(el.textContent==null?'':el.textContent),complete=wholeText(text),preview=previewText(text),rect={x:Math.round(r.left),y:Math.round(r.top),w:Math.round(r.width),h:Math.round(r.height)},legacy={source:'dezin',type:'selected',selector:picked.locator.selector,tag:tag,textPreview:preview,textComplete:complete,rect:rect,styles:styles(el),attrs:attrs(el)},direct={source:'dezin',type:'element-selected',locator:picked.locator,tag:tag,textPreview:preview,textComplete:complete,rect:rect,instanceId:picked.instanceId||undefined};if(complete){legacy.text=text;direct.text=text;}selectedEl=el;keyboardEl=null;keyboardIndex=-1;fit(el,selectedBox);if(hoverBox)hoverBox.style.display='none';pinned=true;announce('Selected '+tag+(preview?' '+preview:''));bridge.send(legacy);bridge.send(direct);}
function click(e){if(!on||e.isTrusted!==true)return;e.preventDefault();e.stopPropagation();choose(e.target);}
function candidateList(){var nodes=[];try{nodes=document.querySelectorAll('[data-design-node-id],[data-dezin-id],[data-dezin-node-id],[data-screen-label]');if(!nodes.length)nodes=document.querySelectorAll('button,a[href],input,textarea,select,[role],h1,h2,h3,h4,h5,h6,main,section,article,nav,header,footer');}catch(_){}var result=[];for(var i=0;i<nodes.length&&result.length<512;i++){var el=nodes[i];if(!el||el===hoverBox||el===selectedBox||el===liveRegion)continue;try{var r=el.getBoundingClientRect();if(r.width>0&&r.height>0)result.push(el);}catch(_){}}return result;}
function moveKeyboard(delta,edge){var items=candidateList();if(!items.length){keyboardEl=null;keyboardIndex=-1;announce('No selectable elements found.');return;}if(edge==='start')keyboardIndex=0;else if(edge==='end')keyboardIndex=items.length-1;else if(keyboardIndex<0)keyboardIndex=delta<0?items.length-1:0;else keyboardIndex=(keyboardIndex+delta+items.length)%items.length;keyboardEl=items[keyboardIndex];fit(keyboardEl,hoverBox);try{keyboardEl.scrollIntoView({block:'nearest',inline:'nearest'});}catch(_){}var label=previewText(String(keyboardEl.textContent==null?'':keyboardEl.textContent));announce('Element '+(keyboardIndex+1)+' of '+items.length+', '+keyboardEl.tagName.toLowerCase()+(label?', '+label:'')+'. Press Enter to select.');}
function mode(v){on=v;keyboardEl=null;keyboardIndex=-1;if(v){pinned=false;announce('Element picker active. Use Arrow keys to move, Home or End to jump, Enter to select, and Escape to cancel.');}else announce('Element picker paused.');if(hoverBox)hoverBox.style.display='none';try{document.body.style.cursor=v?'crosshair':'';}catch(_){}}
function clearMark(){pinned=false;selectedEl=null;keyboardEl=null;keyboardIndex=-1;if(hoverBox)hoverBox.style.display='none';if(selectedBox)selectedBox.style.display='none';announce('Selection cleared.');try{document.body.style.cursor='';}catch(_){}}
function key(e){if(e.isTrusted!==true)return;if((on||pinned||selectedEl)&&e.key==='Escape'){e.preventDefault();bridge.send({source:'dezin',type:'cancel'});bridge.send({source:'dezin',type:'element-cleared'});mode(false);clearMark();return;}if(!on)return;var delta=0,edge='';if(e.key==='ArrowDown'||e.key==='ArrowRight')delta=1;else if(e.key==='ArrowUp'||e.key==='ArrowLeft')delta=-1;else if(e.key==='Home')edge='start';else if(e.key==='End')edge='end';else if((e.key==='Enter'||e.key===' ')&&keyboardEl){e.preventDefault();e.stopPropagation();choose(keyboardEl);return;}else return;e.preventDefault();e.stopPropagation();moveKeyboard(delta,edge);}
function focusTarget(selector,rect){var el=null;try{if(selector)el=document.querySelector(selector);}catch(_){}if(el){try{el.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});}catch(_){try{el.scrollIntoView();}catch(__){}}selectedEl=el;fit(el,selectedBox);window.setTimeout(refreshSelected,80);pinned=true;on=false;if(hoverBox)hoverBox.style.display='none';return;}if(rect&&selectedBox){selectedEl=null;fitRect(selectedBox,rect);pinned=true;on=false;if(hoverBox)hoverBox.style.display='none';}}
var syncingScroll=false,lastScrollTop=-1,lastScrollLeft=-1;
function scrollRoot(){return document.scrollingElement||document.documentElement||document.body;}
function scrollPos(){var r=scrollRoot();return{top:Math.round((window.pageYOffset||r&&r.scrollTop||document.body&&document.body.scrollTop||0)),left:Math.round((window.pageXOffset||r&&r.scrollLeft||document.body&&document.body.scrollLeft||0))};}
function setScroll(top,left){syncingScroll=true;top=Number(top)||0;left=Number(left)||0;try{if(window.scrollTo)window.scrollTo(left,top);var r=scrollRoot();if(r){r.scrollTop=top;r.scrollLeft=left;}if(document.documentElement&&document.documentElement!==r){document.documentElement.scrollTop=top;document.documentElement.scrollLeft=left;}if(document.body&&document.body!==r){document.body.scrollTop=top;document.body.scrollLeft=left;}}catch(_){}refreshSelected();window.setTimeout(function(){syncingScroll=false;},50);}
function reportScroll(){if(syncingScroll)return;var p=scrollPos();if(p.top===lastScrollTop&&p.left===lastScrollLeft)return;lastScrollTop=p.top;lastScrollLeft=p.left;bridge.send({source:'dezin',type:'scroll',top:p.top,left:p.left});}
function onScroll(){if(installPicker)refreshSelected();if(installScroll)reportScroll();}
function init(){if(installPicker){mkbox();document.addEventListener('mousemove',move,true);document.addEventListener('click',click,true);window.addEventListener('resize',refreshSelected);document.addEventListener('keydown',key,true);}document.addEventListener('scroll',onScroll,true);if(installScroll)window.addEventListener('scroll',reportScroll,{passive:true});bridge.listen(function(d){if(installPicker&&d.type==='select-mode')mode(!!d.on);else if(installPicker&&d.type==='clear')clearMark();else if(installPicker&&d.type==='focus-target')focusTarget(d.selector,d.rect);else if(installScroll&&d.type==='sync-scroll')setScroll(d.top,d.left);});}
if(document.body)init();else document.addEventListener('DOMContentLoaded',init);
})();</script>`;

/** Inject the picker bridge before </body> (or append) for HTML responses. */
export function injectSelectBridge(html: string): string {
  const i = html.lastIndexOf("</body>");
  return i >= 0 ? html.slice(0, i) + SELECT_BRIDGE + html.slice(i) : html + SELECT_BRIDGE;
}

/**
 * A tiny runtime-error probe injected into served HTML. It listens for uncaught
 * errors, unhandled rejections, console.error calls, and failed fetch/XHR requests,
 * classifies them as fatal/nonfatal based on whether the page has rendered content,
 * de-dupes bursts, and posts them to `parent` via postMessage. It also posts a
 * first-paint heartbeat once the page has visible content. Kept as a separate
 * <script> (not merged into SELECT_BRIDGE) so it can't regress the picker; this
 * string must stay byte-identical to the one in
 * content/templates/react-vite/vite.config.js.
 */
const RUNTIME_PROBE = `<script data-dezin-runtime-probe>(function(){
var bridge=window.__dezinBridgeTransport;
if(!bridge){bridge=(function(){
  var nonce='';
  var parentOrigin='',trustedParentOrigin='',port=null,transportGeneration=0,queue=[],listeners=[],opaqueSelf=String(window.origin||'')==='null',frameValue=null,frameGlobalReady=false,frameRootBackground,frameBodyBackground,frameRejectReason='invalid-frame',frameConsumptionGeneration=0,pendingFrameConsumption=null,privatePrototypeBindings=[],prototypeInstalled=false,prototypeSubmitArm=null,prototypeNow=Date.now,prototypeFreeze=Object.freeze,pickerOn=false,pickerInstalled=false,pickerKeyboardEl=null,pickerKeyboardIndex=-1,nativeApply=Reflect.apply,nativeStopImmediate=typeof Event!=='undefined'&&Event.prototype?Event.prototype.stopImmediatePropagation:null,nativePortPost=typeof MessagePort!=='undefined'&&MessagePort.prototype?MessagePort.prototype.postMessage:null,nativePortStart=typeof MessagePort!=='undefined'&&MessagePort.prototype?MessagePort.prototype.start:null,nativePortClose=typeof MessagePort!=='undefined'&&MessagePort.prototype?MessagePort.prototype.close:null,nativePortListen=typeof MessagePort!=='undefined'&&MessagePort.prototype?MessagePort.prototype.addEventListener:null,INVALID={};
  try{Object.defineProperty(window,'__DEZIN_RENDER_FRAME__',{get:function(){return frameValue;},configurable:false});frameGlobalReady=true;}catch(_){}
  function envelope(data){var out={},key;for(key in data)if(Object.prototype.hasOwnProperty.call(data,key))out[key]=data[key];out.nonce=nonce;out.protocol=1;return out;}
  function deliver(data){if(port){if(nativePortPost)nativeApply(nativePortPost,port,[data]);else port.postMessage(data);}else if(parentOrigin)parent.postMessage(data,parentOrigin);}
  function send(data){if(!nonce){queue.push(data);if(queue.length>50)queue.shift();return;}var out=envelope(data);if(!port&&!parentOrigin){queue.push(out);if(queue.length>50)queue.shift();return;}deliver(out);}
  function finite(v){return typeof v==='number'&&isFinite(v)&&Math.abs(v)<=100000000;}
  function own(o,k){return Object.prototype.hasOwnProperty.call(o,k);}
  function boundedText(v,max){return typeof v==='string'&&v.length>0&&v.length<=max&&!/[\\u0000-\\u001f\\u007f]/.test(v);}
  function cloneJson(v,state,depth){state.nodes++;if(state.nodes>4096||depth>16)return INVALID;if(v===null||typeof v==='boolean')return v;if(typeof v==='number')return isFinite(v)?v:INVALID;if(typeof v==='string')return v.length<=8192?v:INVALID;if(Array.isArray(v)){if(v.length>256)return INVALID;var a=[];for(var i=0;i<v.length;i++){var item=cloneJson(v[i],state,depth+1);if(item===INVALID)return INVALID;a.push(item);}return a;}if(!v||typeof v!=='object'||Object.prototype.toString.call(v)!=='[object Object]')return INVALID;var keys=Object.keys(v);if(keys.length>256)return INVALID;var out={};for(var j=0;j<keys.length;j++){var key=keys[j];if(!boundedText(key,256)||key==='__proto__'||key==='prototype'||key==='constructor')return INVALID;var next=cloneJson(v[key],state,depth+1);if(next===INVALID)return INVALID;Object.defineProperty(out,key,{value:next,enumerable:true,writable:false,configurable:false});}return out;}
  function freezeJson(v,seen){if(!v||typeof v!=='object'||seen.indexOf(v)>=0)return v;seen.push(v);var keys=Object.keys(v);for(var i=0;i<keys.length;i++)freezeJson(v[keys[i]],seen);try{Object.freeze(v);}catch(_){}return v;}
  function canonicalJson(v){if(v===null||typeof v==='boolean'||typeof v==='number'||typeof v==='string')return JSON.stringify(v);if(Array.isArray(v)){var items=[];for(var i=0;i<v.length;i++)items.push(canonicalJson(v[i]));return'['+items.join(',')+']';}var keys=Object.keys(v).sort(),parts=[];for(var j=0;j<keys.length;j++)parts.push(JSON.stringify(keys[j])+':'+canonicalJson(v[keys[j]]));return'{'+parts.join(',')+'}';}
  function frameStateDigest(frame){if(typeof crypto==='undefined'||!crypto.subtle||typeof crypto.subtle.digest!=='function'||typeof TextEncoder==='undefined')return null;var state={fixture:own(frame,'fixture')?frame.fixture:null,initialState:own(frame,'initialState')?frame.initialState:null},bytes=new TextEncoder().encode(canonicalJson(state));return crypto.subtle.digest('SHA-256',bytes).then(function(buffer){var view=new Uint8Array(buffer),out='';for(var i=0;i<view.length;i++)out+=view[i].toString(16).padStart(2,'0');return out;});}
  function frameConsumptionNonce(){if(typeof crypto==='undefined'||typeof crypto.getRandomValues!=='function')return'';var bytes=new Uint8Array(24),out='';crypto.getRandomValues(bytes);for(var i=0;i<bytes.length;i++)out+=bytes[i].toString(16).padStart(2,'0');return out;}
  function kernelFrame(id){try{var context=window.__DEZIN_RENDER_CONTEXT__,kernel=context&&context.kernel,frames=kernel&&kernel.responsiveFrames;if(!Array.isArray(frames))return null;for(var i=0;i<frames.length;i++)if(frames[i]&&frames[i].id===id)return frames[i];}catch(_){}return null;}
  function gradientStart(v){return /^(?:repeating-)?(?:linear|radial|conic)-gradient\\s*\\(/i.test(v.trim());}
  function gradientList(v){var depth=0,start=0;for(var i=0;i<v.length;i++){var c=v.charAt(i);if(c==='(')depth++;else if(c===')'){depth--;if(depth<0)return false;}else if(c===','&&depth===0){if(!gradientStart(v.slice(start,i)))return false;start=i+1;}}return depth===0&&gradientStart(v.slice(start));}
  function backgroundContextFree(v){return !/(?:^|[^a-z0-9_-])(?:currentcolor|inherit|initial|revert|revert-layer|unset|accentcolor|accentcolortext|activetext|buttonborder|buttonface|buttontext|canvas|canvastext|field|fieldtext|graytext|highlight|highlighttext|linktext|mark|marktext|selecteditem|selecteditemtext|visitedtext|activeborder|activecaption|appworkspace|background|buttonhighlight|buttonshadow|captiontext|inactiveborder|inactivecaption|inactivecaptiontext|infobackground|infotext|menu|menutext|scrollbar|threeddarkshadow|threedface|threedhighlight|threedlightshadow|threedshadow|window|windowframe|windowtext|-webkit-focus-ring-color)(?:$|[^a-z0-9_-])/i.test(v)&&!/(?:^|[^a-z0-9_-])light-dark\\s*\\(/i.test(v);}
  function backgroundOk(v){if(!boundedText(v,4096)||!backgroundContextFree(v)||v.indexOf(String.fromCharCode(92))>=0||v.indexOf('/*')>=0||/[;{}@]/.test(v)||/(?:^|[^a-z0-9_-])(?:url|image-set|-webkit-image-set|cross-fade|element|paint|var|env|attr)\\s*\\(/i.test(v))return false;try{if(typeof CSS==='undefined'||typeof CSS.supports!=='function')return false;if(v.trim().toLowerCase()==='none'||CSS.supports('color',v))return true;return gradientList(v)&&CSS.supports('background-image',v);}catch(_){return false;}}
  function rejectFrame(reason){frameRejectReason=reason;return null;}
  function normalizeFrame(d){if(!frameGlobalReady)return rejectFrame('render-frame-unavailable');if(!boundedText(d.frameId,256))return rejectFrame('invalid-frame-id');if(own(d,'frameAttemptId')&&!boundedText(d.frameAttemptId,128))return rejectFrame('invalid-frame-attempt');var fallback=kernelFrame(d.frameId),frame={protocol:'dezin-frame-v1',frameId:d.frameId},initial=own(d,'initialState')?d.initialState:(fallback?fallback.initialState:undefined),fixture=own(d,'fixture')?d.fixture:(fallback?fallback.fixture:undefined),background=own(d,'background')?d.background:(fallback?fallback.background:undefined);if(own(d,'frameAttemptId'))frame.frameAttemptId=d.frameAttemptId;if(initial!==undefined){if(!boundedText(initial,256))return rejectFrame('invalid-initial-state');frame.initialState=initial;}if(fixture!==undefined){if(!fixture||typeof fixture!=='object'||Array.isArray(fixture))return rejectFrame('invalid-fixture');fixture=cloneJson(fixture,{nodes:0},0);if(fixture===INVALID)return rejectFrame('invalid-fixture');frame.fixture=fixture;}if(background!==undefined){if(!backgroundOk(background))return rejectFrame('unsafe-background');frame.background=background;}try{if(JSON.stringify(frame).length>65536)return rejectFrame('frame-too-large');}catch(_){return rejectFrame('invalid-frame');}return freezeJson(frame,[]);}
  function rememberFrameStyle(style){return[style.background||'',style.getPropertyPriority('background')||'',style.transition||'',style.getPropertyPriority('transition')||'',style.animation||'',style.getPropertyPriority('animation')||''];}
  function paintBackground(style,saved,background){if(background===null){style.setProperty('background',saved[0],saved[1]);style.setProperty('transition',saved[2],saved[3]);style.setProperty('animation',saved[4],saved[5]);}else{style.setProperty('transition','none','important');style.setProperty('animation','none','important');style.setProperty('background',background,'important');}}
  function paintFrame(){var root=document.documentElement,body=document.body;if(!root||!root.style)return;if(frameRootBackground===undefined)frameRootBackground=rememberFrameStyle(root.style);if(body&&frameBodyBackground===undefined)frameBodyBackground=rememberFrameStyle(body.style);var background=frameValue&&own(frameValue,'background')?frameValue.background:null;paintBackground(root.style,frameRootBackground,background);if(body&&body.style)paintBackground(body.style,frameBodyBackground,background===null?null:'transparent');try{root.setAttribute('data-dezin-frame-id',frameValue?frameValue.frameId:'');}catch(_){}}
  function frameReply(type,frame,reason){send({source:'dezin',type:type,frameId:frame.frameId,frameAttemptId:frame.frameAttemptId,reason:reason});}
  function clearFrameConsumption(){var pending=pendingFrameConsumption;if(!pending)return null;pendingFrameConsumption=null;if(pending.timer!==null)clearTimeout(pending.timer);return pending;}
  function rejectPendingFrame(reason){var pending=clearFrameConsumption();if(pending)frameReply('frame-rejected',pending.frame,reason);}
  function frameEvent(frame,consumption){var detail={},keys=Object.keys(frame);for(var i=0;i<keys.length;i++)Object.defineProperty(detail,keys[i],{value:frame[keys[i]],enumerable:true,writable:false,configurable:false});Object.defineProperty(detail,'consumption',{value:freezeJson(consumption,[]),enumerable:true,writable:false,configurable:false});return new CustomEvent('dezin:frame-change',{detail:freezeJson(detail,[])});}
  function consumeFrameReceipt(event){var pending=pendingFrameConsumption,d=event&&event.detail;if(!pending||!exactKeys(d,['source','nonce','frameAttemptId','digest']))return;if(d.source!=='dezin-artifact'||d.nonce!==pending.nonce||d.frameAttemptId!==pending.frame.frameAttemptId)return;if(d.digest!==pending.digest){rejectPendingFrame('frame-consumption-mismatch');return;}clearFrameConsumption();frameReply('frame-applied',pending.frame,'consumed');}
  window.addEventListener('dezin:frame-consumed',consumeFrameReceipt);
  function applyFrame(d){var frame=normalizeFrame(d);if(!frame)return frameRejectReason;frameConsumptionGeneration++;rejectPendingFrame('frame-consumption-superseded');var stateful=own(frame,'initialState')||own(frame,'fixture');if(!stateful){var legacyEvent;try{legacyEvent=new CustomEvent('dezin:frame-change',{detail:frame});}catch(_){return'frame-event-unavailable';}frameValue=frame;paintFrame();if(!document.body)document.addEventListener('DOMContentLoaded',paintFrame,{once:true});try{window.dispatchEvent(legacyEvent);}catch(_){}frameReply('frame-applied',frame,'applied');return'';}if(!boundedText(frame.frameAttemptId,128))return'missing-frame-attempt';var generation=frameConsumptionGeneration,receiptNonce=frameConsumptionNonce(),digestPromise=frameStateDigest(frame);if(!receiptNonce||!digestPromise)return'frame-consumption-unavailable';var pending={generation:generation,frame:frame,nonce:receiptNonce,digest:'',timer:null};pendingFrameConsumption=pending;return digestPromise.then(function(digest){if(pendingFrameConsumption!==pending||generation!==frameConsumptionGeneration)return'';pending.digest=digest;var event;try{event=frameEvent(frame,{protocol:'dezin-frame-consumption-v1',nonce:receiptNonce,frameAttemptId:frame.frameAttemptId,digest:digest});}catch(_){clearFrameConsumption();return'frame-event-unavailable';}frameValue=frame;paintFrame();if(!document.body)document.addEventListener('DOMContentLoaded',paintFrame,{once:true});pending.timer=setTimeout(function(){if(pendingFrameConsumption===pending)rejectPendingFrame('frame-consumption-timeout');},1000);try{window.dispatchEvent(event);}catch(_){clearFrameConsumption();return'frame-event-unavailable';}return'';},function(){if(pendingFrameConsumption===pending)clearFrameConsumption();return'frame-consumption-unavailable';});}
  function plain(v){return!!v&&typeof v==='object'&&!Array.isArray(v)&&Object.prototype.toString.call(v)==='[object Object]';}
  function exactKeys(v,allowed){if(!plain(v))return false;var keys=Object.keys(v);if(keys.length!==allowed.length)return false;for(var i=0;i<keys.length;i++)if(allowed.indexOf(keys[i])<0)return false;return true;}
  function onlyKeys(v,allowed){if(!plain(v))return false;var keys=Object.keys(v);for(var i=0;i<keys.length;i++)if(allowed.indexOf(keys[i])<0)return false;return true;}
  function prototypeLocator(v){return onlyKeys(v,['designNodeId','sourcePath','selector'])&&boundedText(v.designNodeId,256)&&(v.sourcePath===undefined||boundedText(v.sourcePath,1024))&&(v.selector===undefined||boundedText(v.selector,4096));}
  function prototypeBindings(v){if(!Array.isArray(v)||v.length>64)return false;for(var i=0;i<v.length;i++){var item=v[i];if(!exactKeys(item,['bindingId','locator','trigger'])||!boundedText(item.bindingId,128)||!prototypeLocator(item.locator)||(item.trigger!=='click'&&item.trigger!=='submit'))return false;}return true;}
  function prototypeAttr(el,name){try{return el&&el.getAttribute?el.getAttribute(name)||'':'';}catch(_){return '';}}
  function prototypeSourcePath(el){var node=el;while(node&&node.nodeType===1){var value=prototypeAttr(node,'data-dezin-source-path')||prototypeAttr(node,'data-source-path');if(value)return value;node=node.parentElement;}return '';}
  function prototypeElementMatch(el,loc){if(!el||el.nodeType!==1)return false;var design=prototypeAttr(el,'data-design-node-id')||prototypeAttr(el,'data-dezin-id')||prototypeAttr(el,'data-dezin-node-id');if(design!==loc.designNodeId)return false;if(own(loc,'sourcePath')&&prototypeSourcePath(el)!==loc.sourcePath)return false;if(own(loc,'selector')){try{if(typeof el.matches!=='function'||!el.matches(loc.selector))return false;}catch(_){return false;}}return true;}
  function prototypePath(e){var path=[];try{if(typeof e.composedPath==='function')path=e.composedPath();}catch(_){}if(!Array.isArray(path)||!path.length){path=[];var node=e.target;while(node){path.push(node);node=node.parentElement;}}return path;}
  function prototypeMatch(path,trigger){for(var p=0;p<path.length;p++){var el=path[p];for(var i=0;i<privatePrototypeBindings.length;i++){var candidate=privatePrototypeBindings[i];if(candidate.trigger===trigger&&prototypeElementMatch(el,candidate.locator))return{binding:candidate,element:el};}}return null;}
  function prototypeSubmitter(path){for(var i=0;i<path.length;i++){var el=path[i],tag=String(el&&el.tagName||'').toLowerCase(),type=String(el&&el.type||prototypeAttr(el,'type')||'').toLowerCase();if(tag==='button'&&(type===''||type==='submit')||tag==='input'&&(type==='submit'||type==='image'))return el;}return null;}
  function armPrototypeSubmit(e,kind){if(!e||e.isTrusted!==true)return;if(kind==='keyboard'&&(e.repeat===true||e.altKey===true||e.ctrlKey===true||e.metaKey===true||e.key!=='Enter'&&e.key!==' '))return;var path=prototypePath(e),match=prototypeMatch(path,'submit'),submitter=prototypeSubmitter(path);if(!match||kind==='pointer'&&!submitter||kind==='keyboard'&&e.key===' '&&!submitter)return;prototypeSubmitArm={element:match.element,submitter:submitter,expiresAt:prototypeNow()+1500};}
  function consumePrototypeSubmit(e,match){var arm=prototypeSubmitArm;prototypeSubmitArm=null;if(!arm||!match||prototypeNow()>arm.expiresAt||arm.element!==match.element)return false;var submitter=e&&e.submitter||null;return arm.submitter===null||submitter===arm.submitter;}
  function prototypeEvent(e,trigger){if(!e||e.isTrusted!==true)return;var path=prototypePath(e),match=prototypeMatch(path,trigger);if(trigger==='submit'&&!consumePrototypeSubmit(e,match))return;if(!match)return;if(typeof e.preventDefault==='function')e.preventDefault();if(typeof e.stopPropagation==='function')e.stopPropagation();if(typeof e.stopImmediatePropagation==='function')e.stopImmediatePropagation();send({source:'dezin',type:'prototype-binding-activated',bindingId:match.binding.bindingId,locator:match.binding.locator,trigger:trigger});}
  function installPrototype(){if(prototypeInstalled||!document||typeof document.addEventListener!=='function')return;prototypeInstalled=true;document.addEventListener('pointerdown',function(e){armPrototypeSubmit(e,'pointer');},true);document.addEventListener('keydown',function(e){if(e&&e.isTrusted===true&&e.key==='Escape'){send({source:'dezin',type:'prototype-exit-requested'});return;}armPrototypeSubmit(e,'keyboard');},true);document.addEventListener('click',function(e){prototypeEvent(e,'click');},true);document.addEventListener('submit',function(e){prototypeEvent(e,'submit');},true);}
  function setPrototypeBindings(bindings){var next=[];for(var i=0;i<bindings.length;i++){var item=bindings[i],loc=item.locator,copy={designNodeId:loc.designNodeId};if(own(loc,'sourcePath'))copy.sourcePath=loc.sourcePath;if(own(loc,'selector'))copy.selector=loc.selector;try{prototypeFreeze(copy);}catch(_){}var descriptor={bindingId:item.bindingId,locator:copy,trigger:item.trigger};try{prototypeFreeze(descriptor);}catch(_){}next.push(descriptor);}try{prototypeFreeze(next);}catch(_){}privatePrototypeBindings=next;installPrototype();}
  function pickerCss(v){try{return CSS&&CSS.escape?CSS.escape(v):v.replace(/[^a-zA-Z0-9_-]/g,'\\\\$&');}catch(_){return v;}}
  function pickerNth(el){var i=1,n=el;while((n=n.previousElementSibling)){if(n.tagName===el.tagName)i++;}return i;}
  function pickerStable(el){var design=prototypeAttr(el,'data-design-node-id');if(design)return'[data-design-node-id="'+design.replace(/\\\\/g,'\\\\\\\\').replace(/"/g,'\\\\"')+'"]';var target=prototypeAttr(el,'data-dezin-id');if(target)return'[data-dezin-id="'+target.replace(/\\\\/g,'\\\\\\\\').replace(/"/g,'\\\\"')+'"]';var node=prototypeAttr(el,'data-dezin-node-id');if(node)return'[data-dezin-node-id="'+node.replace(/\\\\/g,'\\\\\\\\').replace(/"/g,'\\\\"')+'"]';var label=prototypeAttr(el,'data-screen-label');if(label)return'[data-screen-label="'+label.replace(/\\\\/g,'\\\\\\\\').replace(/"/g,'\\\\"')+'"]';if(el.id)return String(el.tagName||'').toLowerCase()+'#'+pickerCss(String(el.id));return'';}
  function pickerPath(el){if(!el||el===document.body||el===document.documentElement)return el?String(el.tagName||'').toLowerCase():'';var exact=pickerStable(el);if(exact)return exact;var parts=[],n=el,depth=0;while(n&&n.nodeType===1&&n!==document.body&&depth<5){var stable=pickerStable(n);if(stable){parts.unshift(stable);break;}var part=String(n.tagName||'').toLowerCase();if(n.classList&&n.classList.length)part+='.'+[].slice.call(n.classList).slice(0,2).map(pickerCss).join('.');part+=':nth-of-type('+pickerNth(n)+')';parts.unshift(part);n=n.parentElement;depth++;}return parts.join(' > ');}
  function pickerLocator(el){var n=el,marked=null;while(n&&n.nodeType===1&&n!==document.body){if(prototypeAttr(n,'data-design-node-id')||prototypeAttr(n,'data-dezin-id')||prototypeAttr(n,'data-dezin-node-id')){marked=n;break;}n=n.parentElement;}var target=marked||el,selector=pickerPath(target),designNodeId=prototypeAttr(target,'data-design-node-id')||prototypeAttr(target,'data-dezin-id')||prototypeAttr(target,'data-dezin-node-id')||'selector:'+selector,sourceNode=target,sourcePath='';while(sourceNode&&sourceNode.nodeType===1&&!sourcePath){sourcePath=prototypeAttr(sourceNode,'data-dezin-source-path')||prototypeAttr(sourceNode,'data-source-path');sourceNode=sourceNode.parentElement;}var locator={designNodeId:String(designNodeId),selector:selector};if(sourcePath)locator.sourcePath=sourcePath;return{element:target,locator:locator,instanceId:prototypeAttr(target,'data-dezin-instance-id')};}
  function pickerAttrs(el){try{var cls=typeof el.className==='string'?el.className:prototypeAttr(el,'class');return{id:el.id||'',className:cls,role:prototypeAttr(el,'role'),ariaLabel:prototypeAttr(el,'aria-label'),screenLabel:prototypeAttr(el,'data-screen-label'),designNodeId:prototypeAttr(el,'data-design-node-id'),dezinId:prototypeAttr(el,'data-dezin-id')||prototypeAttr(el,'data-dezin-node-id'),sourcePath:prototypeAttr(el,'data-dezin-source-path')||prototypeAttr(el,'data-source-path'),instanceId:prototypeAttr(el,'data-dezin-instance-id'),href:prototypeAttr(el,'href'),src:prototypeAttr(el,'src')};}catch(_){return{};}}
  function pickerStyles(el){try{var s=getComputedStyle(el);return{display:s.display,position:s.position,top:s.top,right:s.right,bottom:s.bottom,left:s.left,zIndex:s.zIndex,width:s.width,height:s.height,minWidth:s.minWidth,maxWidth:s.maxWidth,minHeight:s.minHeight,maxHeight:s.maxHeight,overflow:s.overflow,overflowX:s.overflowX,overflowY:s.overflowY,flexDirection:s.flexDirection,flexWrap:s.flexWrap,justifyContent:s.justifyContent,alignItems:s.alignItems,alignContent:s.alignContent,gap:s.gap,rowGap:s.rowGap,columnGap:s.columnGap,gridTemplateColumns:s.gridTemplateColumns,gridTemplateRows:s.gridTemplateRows,padding:s.padding,margin:s.margin,color:s.color,background:s.backgroundColor,backgroundImage:s.backgroundImage,fontFamily:s.fontFamily,fontSize:s.fontSize,fontWeight:s.fontWeight,lineHeight:s.lineHeight,letterSpacing:s.letterSpacing,textAlign:s.textAlign,textTransform:s.textTransform,borderRadius:s.borderRadius,opacity:s.opacity,borderColor:s.borderColor,borderWidth:s.borderWidth,borderStyle:s.borderStyle,borderTopColor:s.borderTopColor,borderTopWidth:s.borderTopWidth,borderTopStyle:s.borderTopStyle,borderRightColor:s.borderRightColor,borderRightWidth:s.borderRightWidth,borderRightStyle:s.borderRightStyle,borderBottomColor:s.borderBottomColor,borderBottomWidth:s.borderBottomWidth,borderBottomStyle:s.borderBottomStyle,borderLeftColor:s.borderLeftColor,borderLeftWidth:s.borderLeftWidth,borderLeftStyle:s.borderLeftStyle,outlineColor:s.outlineColor,outlineWidth:s.outlineWidth,outlineStyle:s.outlineStyle,boxShadow:s.boxShadow,filter:s.filter,backdropFilter:s.backdropFilter,transform:s.transform,mixBlendMode:s.mixBlendMode};}catch(_){return{};}}
  function pickerWholeText(value){if(value.length>100000)return false;for(var i=0;i<value.length;i++){var code=value.charCodeAt(i);if(code>=55296&&code<=56319){var next=value.charCodeAt(i+1);if(next<56320||next>57343)return false;i++;}else if(code>=56320&&code<=57343)return false;}return true;}
  function pickerChoose(target){if(!target||target.nodeType!==1)return;var picked=pickerLocator(target),el=picked.element,r;try{r=el.getBoundingClientRect();}catch(_){return;}if(!r||!finite(r.left)||!finite(r.top)||!finite(r.width)||!finite(r.height)||r.width<0||r.height<0)return;var text=String(el.textContent==null?'':el.textContent),complete=pickerWholeText(text),preview=text.replace(/\\s+/g,' ').trim().slice(0,160),tag=String(el.tagName||'').toLowerCase().slice(0,64),rect={x:Math.round(r.left),y:Math.round(r.top),w:Math.round(r.width),h:Math.round(r.height)},legacy={source:'dezin',type:'selected',selector:picked.locator.selector,tag:tag,textPreview:preview,textComplete:complete,rect:rect,styles:pickerStyles(el),attrs:pickerAttrs(el)},direct={source:'dezin',type:'element-selected',locator:picked.locator,tag:tag,textPreview:preview,textComplete:complete,rect:rect};if(picked.instanceId)direct.instanceId=picked.instanceId;if(complete){legacy.text=text;direct.text=text;}pickerKeyboardEl=null;pickerKeyboardIndex=-1;send(legacy);send(direct);}
  function pickerCandidates(){var nodes=[];try{nodes=document.querySelectorAll('[data-design-node-id],[data-dezin-id],[data-dezin-node-id],[data-screen-label]');if(!nodes.length)nodes=document.querySelectorAll('button,a[href],input,textarea,select,[role],h1,h2,h3,h4,h5,h6,main,section,article,nav,header,footer');}catch(_){}var result=[];for(var i=0;i<nodes.length&&result.length<512;i++){var el=nodes[i];try{var r=el.getBoundingClientRect();if(r.width>0&&r.height>0)result.push(el);}catch(_){}}return result;}
  function pickerMove(delta,edge){var items=pickerCandidates();if(!items.length){pickerKeyboardEl=null;pickerKeyboardIndex=-1;return;}if(edge==='start')pickerKeyboardIndex=0;else if(edge==='end')pickerKeyboardIndex=items.length-1;else if(pickerKeyboardIndex<0)pickerKeyboardIndex=delta<0?items.length-1:0;else pickerKeyboardIndex=(pickerKeyboardIndex+delta+items.length)%items.length;pickerKeyboardEl=items[pickerKeyboardIndex];}
  function pickerClick(e){if(!pickerOn||!e||e.isTrusted!==true)return;pickerChoose(e.target);}
  function pickerKey(e){if(!pickerOn||!e||e.isTrusted!==true)return;if(e.key==='Escape'){pickerOn=false;pickerKeyboardEl=null;pickerKeyboardIndex=-1;send({source:'dezin',type:'cancel'});send({source:'dezin',type:'element-cleared'});return;}var delta=0,edge='';if(e.key==='ArrowDown'||e.key==='ArrowRight')delta=1;else if(e.key==='ArrowUp'||e.key==='ArrowLeft')delta=-1;else if(e.key==='Home')edge='start';else if(e.key==='End')edge='end';else if((e.key==='Enter'||e.key===' ')&&pickerKeyboardEl){pickerChoose(pickerKeyboardEl);return;}else return;pickerMove(delta,edge);}
  function installPrivatePicker(){if(pickerInstalled||!window||typeof window.addEventListener!=='function')return;pickerInstalled=true;window.addEventListener('click',pickerClick,true);window.addEventListener('keydown',pickerKey,true);}
  function command(d){if(!plain(d)||d.source!=='dezin-parent'||d.protocol!==1||d.nonce!==nonce||typeof d.type!=='string')return false;var base=['source','type','protocol','nonce'];if(d.type==='select-mode')return exactKeys(d,base.concat(['on']))&&typeof d.on==='boolean';if(d.type==='clear')return exactKeys(d,base);if(d.type==='sync-scroll')return exactKeys(d,base.concat(['top','left']))&&finite(d.top)&&finite(d.left);if(d.type==='focus-target'){var selector=d.selector,rect=d.rect;return onlyKeys(d,base.concat(['selector','rect']))&&(selector===undefined||(typeof selector==='string'&&selector.length<=4096))&&(rect===undefined||(exactKeys(rect,['x','y','w','h'])&&finite(rect.x)&&finite(rect.y)&&finite(rect.w)&&finite(rect.h)));}if(d.type==='set-prototype-bindings')return exactKeys(d,base.concat(['bindings']))&&prototypeBindings(d.bindings);if(d.type==='set-frame')return onlyKeys(d,base.concat(['frameId','frameAttemptId','initialState','fixture','background']));return false;}
  function dispatch(d){if(!command(d))return;if(d.type==='set-frame'){var rejected=function(reason){if(reason)send({source:'dezin',type:'frame-rejected',frameId:boundedText(d.frameId,256)?d.frameId:null,frameAttemptId:boundedText(d.frameAttemptId,128)?d.frameAttemptId:undefined,reason:reason});},result=applyFrame(d);if(result&&typeof result.then==='function')result.then(rejected,function(){rejected('frame-consumption-unavailable');});else rejected(result);return;}if(d.type==='set-prototype-bindings'){setPrototypeBindings(d.bindings);return;}if(d.type==='select-mode'){pickerOn=!!d.on;pickerKeyboardEl=null;pickerKeyboardIndex=-1;}else if(d.type==='clear'||d.type==='focus-target'){pickerOn=false;pickerKeyboardEl=null;pickerKeyboardIndex=-1;}for(var i=0;i<listeners.length;i++)try{listeners[i](d);}catch(_){}}
  function flush(){var pending=queue;queue=[];for(var i=0;i<pending.length;i++)deliver(own(pending[i],'nonce')?pending[i]:envelope(pending[i]));}
  function init(e,d){if(!e||e.isTrusted!==true||!d||d.source!=='dezin-parent'||d.type!=='bridge-init'||d.protocol!==1||!boundedText(d.nonce,43)||d.nonce.length!==43||!/^[a-zA-Z0-9_-]{43}$/.test(d.nonce)||nonce&&d.nonce!==nonce||e.source!==parent)return false;var offered=e.ports&&e.ports[0];if(!offered||!e.origin||trustedParentOrigin&&e.origin!==trustedParentOrigin)return false;if(!nonce)nonce=d.nonce;if(!trustedParentOrigin)trustedParentOrigin=e.origin;if(port){try{if(nativePortClose)nativeApply(nativePortClose,port,[]);else if(port.close)port.close();}catch(_){}port=null;}parentOrigin='';transportGeneration++;var generation=transportGeneration,receive=function(message){if(generation===transportGeneration)dispatch(message.data);};port=offered;if(nativePortListen)nativeApply(nativePortListen,port,['message',receive]);else port.onmessage=receive;if(nativePortStart)nativeApply(nativePortStart,port,[]);else if(port.start)port.start();send({source:'dezin',type:'bridge-ready',protocol:1});flush();return true;}
  function consumeBridgeInit(e){try{if(nativeStopImmediate)nativeApply(nativeStopImmediate,e,[]);else if(typeof e.stopImmediatePropagation==='function')e.stopImmediatePropagation();}catch(_){}}
  window.addEventListener('message',function(e){var d=e.data;if(d&&d.type==='bridge-init'){if(init(e,d))consumeBridgeInit(e);return;}if(port||!parentOrigin||e.source!==parent||e.origin!==parentOrigin||!d||d.nonce!==nonce)return;dispatch(d);},true);
  installPrivatePicker();
  function publicType(type){return type==='scroll'||type==='runtime-error';}
  function publicSend(data){if(!plain(data)||data.source!=='dezin'||!publicType(data.type))return false;if(!nonce){queue.push(data);if(queue.length>50)queue.shift();return true;}var out;try{out=envelope(data);}catch(_){return false;}if(!port&&!parentOrigin){queue.push(out);if(queue.length>50)queue.shift();return true;}deliver(out);return true;}
  return{send:publicSend,listen:function(listener){listeners.push(listener);}};
})();try{Object.defineProperty(window,'__dezinBridgeTransport',{value:bridge,writable:false,configurable:false});}catch(_){window.__dezinBridgeTransport=bridge;}}
if(window.__dezinRuntimeProbe)return;window.__dezinRuntimeProbe=1;
var MAXLEN=2000,SIGCAP=50,PREFRAMECAP=16,WIN=1000,seen={},order=[],preFrame=[],fatalSeen=false;
function hasContent(){try{var b=document.body;return !!(b&&b.scrollHeight>40&&(b.innerText||'').trim().length>20);}catch(_){return true;}}
function trunc(s){s=String(s==null?'':s);return s.length>MAXLEN?s.slice(0,MAXLEN):s;}
function safe(o){try{return JSON.stringify(o);}catch(_){return String(o);}}
function frameContext(){try{var frame=window.__DEZIN_RENDER_FRAME__;return frame&&typeof frame.frameId==='string'?frame:null;}catch(_){return null;}}
function emitDiagnostic(payload){var frame=frameContext(),attempt=frame&&frame.frameAttemptId;if(!frame||typeof attempt!=='string'||!attempt||attempt.length>128){if(preFrame.length>=PREFRAMECAP)preFrame.shift();preFrame.push(payload);return;}payload.frameId=frame.frameId;payload.frameAttemptId=attempt;try{bridge.send(payload);}catch(_){}}
function flushPreFrame(){var frame=frameContext();if(!frame||typeof frame.frameAttemptId!=='string'||!frame.frameAttemptId)return;var pending=preFrame;preFrame=[];for(var i=0;i<pending.length;i++)emitDiagnostic(pending[i]);}
function post(kind,errorType,message,stack,src,line,col){
  if(kind==='fatal')fatalSeen=true;
  var frame=frameContext(),frameId=frame&&frame.frameId,frameAttemptId=frame&&frame.frameAttemptId,sig=errorType+'|'+message+'|'+(src||'')+':'+(line||0)+'|'+(frameId||'')+'|'+(frameAttemptId||''),now=Date.now(),rec=seen[sig];
  if(rec){rec.count++;if(now-rec.last<WIN)return;rec.last=now;}
  else{rec={count:1,last:now};seen[sig]=rec;order.push(sig);if(order.length>SIGCAP)delete seen[order.shift()];}
  emitDiagnostic({source:'dezin',type:'runtime-error',kind:kind,errorType:errorType,message:trunc(message),stack:stack?trunc(stack):undefined,src:src?trunc(src):undefined,line:line,col:col,count:rec.count,at:now});
}
window.addEventListener('dezin:frame-change',flushPreFrame);
function classify(){return hasContent()?'nonfatal':'fatal';}
window.addEventListener('error',function(e){
  var t=e&&e.target;
  if(t&&t!==window&&t.tagName){post('nonfatal','resource','Failed to load '+String(t.tagName).toLowerCase()+' resource',undefined,t.src||t.href||'',0,0);return;}
  post(classify(),'error',(e&&e.message)||'Uncaught error',e&&e.error&&e.error.stack,e&&e.filename,e&&e.lineno,e&&e.colno);
},true);
window.addEventListener('unhandledrejection',function(e){
  var r=e&&e.reason;post(classify(),'unhandledrejection',(r&&r.message)||String(r),r&&r.stack);
});
var _err=console.error;console.error=function(){try{var p=[];for(var i=0;i<arguments.length;i++){var a=arguments[i];p.push(a&&a.stack?a.stack:(a&&typeof a==='object'?safe(a):String(a)));}post('nonfatal','console',p.join(' '));}catch(_){}return _err.apply(console,arguments);};
try{var _f=window.fetch;if(_f)window.fetch=function(){var args=arguments,u=args[0];return _f.apply(this,args).then(function(res){try{if(res&&res.status>=400)post('nonfatal','request',res.status+' '+(res.url||''),undefined,res.url||'');}catch(_){}return res;},function(err){try{post('nonfatal','request','fetch failed '+(typeof u==='string'?u:(u&&u.url)||''),err&&err.stack,typeof u==='string'?u:'');}catch(_){}throw err;});};}catch(_){}
try{var _o=XMLHttpRequest.prototype.open,_s=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(m,u){this.__dezinUrl=u;return _o.apply(this,arguments);};XMLHttpRequest.prototype.send=function(){var x=this;x.addEventListener('load',function(){try{if(x.status>=400)post('nonfatal','request',x.status+' '+(x.__dezinUrl||''),undefined,x.__dezinUrl||'');}catch(_){}});x.addEventListener('error',function(){try{post('nonfatal','request','request failed '+(x.__dezinUrl||''),undefined,x.__dezinUrl||'');}catch(_){}});return _s.apply(this,arguments);};}catch(_){}
var rendered=false,blankDone=false;
function blankCheck(deadline){if(rendered||blankDone)return;if(hasContent()){rendered=true;return;}if(fatalSeen){blankDone=true;return;}if(Date.now()>=deadline){blankDone=true;post('fatal','blank','The preview loaded but rendered nothing.');return;}setTimeout(function(){blankCheck(deadline);},250);}
function startBlank(){blankCheck(Date.now()+12000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',startBlank);else startBlank();
})();</script>`;

/**
 * Inject the runtime-error probe as the first thing inside <head> — before the page's own
 * scripts — so a parse-time throw in an early inline script is still caught. The probe's only
 * DOM-dependent piece (the first-paint heartbeat) already defers to DOMContentLoaded, so
 * running it from <head> is safe. Falls back to after <html>, then to a prepend, if there is
 * no <head>. (The picker bridge stays before </body> because it manipulates the DOM.)
 */
export function injectRuntimeProbe(html: string): string {
  const head = html.match(/<head[^>]*>/i);
  if (head && head.index !== undefined) {
    const at = head.index + head[0].length;
    return html.slice(0, at) + RUNTIME_PROBE + html.slice(at);
  }
  const htmlTag = html.match(/<html[^>]*>/i);
  if (htmlTag && htmlTag.index !== undefined) {
    const at = htmlTag.index + htmlTag[0].length;
    return html.slice(0, at) + RUNTIME_PROBE + html.slice(at);
  }
  return RUNTIME_PROBE + html;
}

/** Resolve a relative request path inside `root`, or null if it escapes. */
export function safeJoin(root: string, rel: string): string | null {
  const target = resolve(root, rel);
  const base = resolve(root);
  if (target !== base && !target.startsWith(base + sep)) return null;
  return target;
}

export async function serveProjectFile(res: ServerResponse, dataDir: string, projectId: string, relPath: string): Promise<void> {
  return serveFileFromBase(res, projectDir(dataDir, projectId), relPath);
}

export async function serveFileFromBase(res: ServerResponse, root: string, relPath: string): Promise<void> {
  const rel = relPath === "" ? "index.html" : relPath;
  const target = safeJoin(root, rel);
  if (!target) {
    sendError(res, 400, "invalid path");
    return;
  }
  try {
    const s = await stat(target);
    const file = s.isDirectory() ? safeJoin(target, "index.html") : target;
    if (!file) {
      sendError(res, 400, "invalid path");
      return;
    }
    const contentType = contentTypeFor(file);
    // Inject the element-picker bridge + runtime-error probe into the previewed HTML document only.
    if (contentType.startsWith("text/html")) {
      const html = injectRuntimeProbe(injectSelectBridge(await readFile(file, "utf8")));
      send(res, 200, html, contentType);
      return;
    }
    const bytes = await readFile(file);
    send(res, 200, bytes, contentType);
  } catch {
    sendError(res, 404, "not found");
  }
}
