import type { ApiClient } from "../lib/api.ts";

/** Build a fake ApiClient for tests; override only the methods a test needs. */
export function makeFakeApi(over: Partial<ApiClient> = {}): ApiClient {
  const notImpl = () => {
    throw new Error("not implemented in fake");
  };
  return {
    listProjects: async () => [],
    createProject: notImpl as ApiClient["createProject"],
    generateProjectTitle: async (id: string) => (over.getProject ? over.getProject(id) : notImpl()),
    getSetup: async () => ({ phase: "ready" as const }),
    getDevServerUrl: async (id: string) => ({ url: `http://127.0.0.1:5300/${id}` }),
    releaseDevServer: async () => {},
    renewPreviewLease: async (leaseId: string) => ({ leaseId, url: "http://127.0.0.1:5300/", expiresAt: Date.now() + 60_000 }),
    releasePreviewLease: async () => {},
    captureProjectCover: async () => ({ captured: false }),
    getProject: notImpl as ApiClient["getProject"],
    getWorkspace: async (projectId) => ({
      status: "unsupported",
      code: "workspace_requires_standard_project",
      projectId,
      projectMode: "prototype",
    }),
    listWorkspaceProposals: async () => [],
    getWorkspaceProposal: notImpl as ApiClient["getWorkspaceProposal"],
    createWorkspaceProposal: notImpl as ApiClient["createWorkspaceProposal"],
    updateWorkspaceProposal: notImpl as ApiClient["updateWorkspaceProposal"],
    approveWorkspaceProposal: notImpl as ApiClient["approveWorkspaceProposal"],
    rejectWorkspaceProposal: notImpl as ApiClient["rejectWorkspaceProposal"],
    applyWorkspaceGraphCommands: notImpl as ApiClient["applyWorkspaceGraphCommands"],
    saveWorkspaceLayout: notImpl as ApiClient["saveWorkspaceLayout"],
    getArtifact: notImpl as ApiClient["getArtifact"],
    listArtifactTracks: async () => [],
    listArtifactRevisions: async () => [],
    getArtifactRevision: notImpl as ApiClient["getArtifactRevision"],
    listWorkspaceSnapshots: async () => [],
    getWorkspaceSnapshot: notImpl as ApiClient["getWorkspaceSnapshot"],
    patchProject: notImpl as ApiClient["patchProject"],
    saveCover: async () => {},
    deleteProject: notImpl as ApiClient["deleteProject"],
    listConversations: async () => [],
    createConversation: notImpl as ApiClient["createConversation"],
    getConversation: notImpl as ApiClient["getConversation"],
    renameConversation: notImpl as ApiClient["renameConversation"],
    deleteConversation: async () => {},
    listVariants: async () => [],
    createVariant: async () => [],
    fanoutVariants: async () => ({ plan: { count: 3 }, created: [], variants: [] }),
    forkMessage: async () => ({ conversationId: "c1", variantId: "v1", variants: [] }),
    activateVariant: async () => [],
    renameVariant: async () => [],
    deleteVariant: async () => [],
    listMessages: async () => [],
    listDesignSystems: async () => [],
    getDesignSystem: notImpl as ApiClient["getDesignSystem"],
    importBrand: notImpl as ApiClient["importBrand"],
    listEffects: async () => [],
    getEffect: notImpl as ApiClient["getEffect"],
    createEffect: notImpl as ApiClient["createEffect"],
    updateEffect: notImpl as ApiClient["updateEffect"],
    listSkills: async () => [],
    createExtensionPairingCode: notImpl as ApiClient["createExtensionPairingCode"],
    listExtensionCredentials: async () => [],
    revokeExtensionCredential: async () => {},
    getSettings: async () => ({
      agentCommand: "claude",
      model: "",
      apiBaseUrl: "",
      apiKey: "",
      defaultDesignSystemId: "modern-minimal",
      customInstructions: "",
      imageApiBaseUrl: "",
      imageApiKey: "",
      imageModel: "",
      removeBackgroundModel: "",
      editRegionModel: "",
      extractLayerModel: "",
      videoApiBaseUrl: "",
      videoApiKey: "",
      videoModel: "",
      aiProviderId: "openai",
      aiProviderEnabled: false,
      aiProviderModels: "gpt-image-1",
      aiProviderOrganization: "",
      aiProviderProfiles: "",
      visualQaEnabled: false,
      autoFixLiveRuntimeErrors: false,
      sharinganAffirmed: false,
      researchEnabled: false,
      researchAgentCommand: "",
      researchModel: "",
      visualQaAgentCommand: "",
      visualQaModel: "",
      autoImproveEnabled: true,
      autoImproveMaxRounds: 8,
    }),
    updateSettings: notImpl as ApiClient["updateSettings"],
    testModelProvider: async () => ({ ok: true, message: "Connected." }),
    listModelProviderModels: async () => ({ models: [] }),
    listAgents: async () => [],
    rescanAgents: async () => [],
    async *scanAgentsStream() {
      yield { type: "done" as const, agents: await (over.rescanAgents ?? (async () => []))() };
    },
    getHealth: async () => ({ ok: true, version: "0.0.0" }),
    optimizePrompt: async (input) => ({ prompt: input.prompt }),
    listFiles: async () => [],
    getFileText: async () => "",
    listRuns: async () => [],
    versionPreviewUrl: (id: string, runId: string) => `/api/projects/${id}/versions/${runId}`,
    getVersionPreview: async (id: string, runId: string) => ({ url: `/api/projects/${id}/versions/${runId}`, mode: "prototype" as const }),
    getVersionText: async () => "",
    getVersionDiff: async () => [],
    restoreVersion: notImpl as ApiClient["restoreVersion"],
    setVersionCover: async () => ({ captured: true }),
    uploadRef: async (_id: string, name: string) => ({ name, path: `.refs/${name}` }),
    parseFig: async (_file, name: string) => ({ name, summary: "" }),
    getCapture: async () => ({ images: [], note: "", source: "" }),
    previewUrl: (id: string) => `/projects/${id}/preview/`,
    refUrl: (id: string, refPath: string) => `/api/projects/${id}/refs/${refPath.replace(/^\.refs\//, "")}`,
    getResearch: async () => ({ exists: false }),
    researchAssetUrl: (id: string, assetPath: string) => `/api/projects/${id}/research/assets/${assetPath.replace(/^assets\//, "")}`,
    researchVisualAssetUrl: (_id: string, p: string) => `/v/${p}`,
    variantPreviewUrl: (id: string, vid: string) => `/api/projects/${id}/variants/${vid}/preview/`,
    exportUrl: (id: string, scope = "source") => `/api/projects/${id}/export${scope === "full" ? "?scope=full" : ""}`,
    importProject: notImpl as ApiClient["importProject"],
    listMoodboards: async () => [],
    createMoodboard: notImpl as ApiClient["createMoodboard"],
    startMoodboard: notImpl as ApiClient["startMoodboard"],
    getMoodboard: notImpl as ApiClient["getMoodboard"],
    patchMoodboard: notImpl as ApiClient["patchMoodboard"],
    deleteMoodboard: notImpl as ApiClient["deleteMoodboard"],
    listMoodboardNodes: async () => [],
    saveMoodboardNodes: async (_id, nodes) =>
      nodes.map((node, index) => ({
        id: node.id ?? `n${index}`,
        boardId: _id,
        type: node.type,
        x: node.x,
        y: node.y,
        width: node.width,
        height: node.height,
        rotation: node.rotation ?? 0,
        zIndex: node.zIndex ?? index,
        data: node.data ?? {},
        createdAt: Date.now(),
        updatedAt: Date.now(),
      })),
    listMoodboardConversations: async () => [],
    createMoodboardConversation: notImpl as ApiClient["createMoodboardConversation"],
    renameMoodboardConversation: notImpl as ApiClient["renameMoodboardConversation"],
    deleteMoodboardConversation: notImpl as ApiClient["deleteMoodboardConversation"],
    listMoodboardMessages: async () => [],
    postMoodboardMessage: async () => ({ messages: [] }),
    uploadMoodboardAsset: notImpl as ApiClient["uploadMoodboardAsset"],
    generateMoodboardImage: notImpl as ApiClient["generateMoodboardImage"],
    // eslint-disable-next-line require-yield
    streamRun: async function* () {},
    // eslint-disable-next-line require-yield
    reattachRun: async function* () {},
    cancelRun: async () => ({ cancelled: true }),
    setRunFeedback: async (runId, feedback) => ({
      run: { id: runId, status: "succeeded", score: 100, repairRounds: 0, lintPassed: true, feedback: feedback ?? null, createdAt: 0, finishedAt: 0 },
    }),
    suggestPreferences: async () => ({ suggestion: "", signals: 0 }),
    startSharingan: async () => {},
    cancelSharingan: async () => {},
    sharinganStatus: async () => ({ phase: "idle", steps: 0, pages: [] }),
    continueSharingan: async () => {},
    focusSharingan: async () => {},
    // eslint-disable-next-line require-yield
    streamSharinganEvents: async function* () {},
    sharinganShotUrl: (id: string, relPath: string) => `/shot/${id}/${relPath}`,
    ...over,
  };
}
